name: report-event
description: 'Sends event data to the MACBIS DevSecOps Metrics API'
inputs:
  args:
    description: Arguments to pass to the report-event program. See cmd/report-event/README.md for documentation
outputs:
  exit-code:
    description: The exit code of the program
  output:
    description: The output of the program (stdout)
  error-output:
    description: The error output of the program (stderr)
runs:
  using: node16 # TODO test node20
  main: build/index.js
