name: Test report-event action

on:
  push:
    branches: [bharvey-action] # TODO update trigger

jobs:
  test:
    # strategy:
    #   matrix:
    #     os: [ubuntu-latest, windows-latest, macos-latest]
    #   fail-fast: false
    # runs-on: ${{ matrix.os }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS creds
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1

    - name: Test report-event action
      id: test-action
      uses: ./
      continue-on-error: true # TODO for now, we're expecting the program to exit 2 when usage is called
      with:
        args: -h # TODO we might decide to report a valid test event to test infrastructure when it is set up

    - name: Assert against outputs
      if: ${{ (steps.test-action.outputs.exit-code != 2)  ||  (!contains(steps.test-action.outputs.output, 'report-event')) }}
      run: |
        echo "Exit code and output did not match expected"
        echo "Exit code: ${{ steps.test-action.outputs.exit-code }}"
        echo "Stdout: ${{ steps.test-action.outputs.output }}"
        echo "Stderr: ${{ steps.test-action.outputs.error-output }}"
        exit 1
